#8 | Add Angular Material and separate components
xonism/internship-project pull request #21
Opened 2023-08-18 07:06 UTC by xonism

2023-08-18 11:23 UTC, ArnasPetraitis requested changes

2023-08-18 11:23 UTC, ArnasPetraitis commented on internship-shop-ui/src/app/components/quantity-picker/quantity-picker.component.ts
> +		if (this.quantity > 1) {
also button could be disabled in that case

2023-08-18 12:04 UTC, JustasVit requested changes

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/app.component.scss
> +		color: whitesmoke !important;
Try not to use !important, if you want to change default angular material component styling, try this: https://betterprogramming.pub/best-way-to-overwrite-angular-materials-styles-e38dc8b84962 .  Also, use color codes in HEX for consistency.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/app.component.ts
> +	title = 'internship-shop';
Where this is used?

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-info/product-info.component.html
> +		<span matListItemLine class="list-line">{{product?.description ?? loadingMessage}}</span>
What if the product does not have a description? Do we really want to always show loading message in this case?

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-info/product-info.component.ts
> +	selector: 'insh-product-info',
selector: 'product-info' or 'app-product-info'

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-info/product-info.component.ts
> +	product: Product | null = null;
No need to have the null part. If there is no input, product will be undefined.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-info/product-info.component.ts
> +	loadingMessage: string = 'Loading..'
If you are going to use it only in renderPrice method, just add it there.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-list/product-list.component.scss
> +			font-family: 'Poppins', sans-serif;
I would suggest to put such things as font-family, sizes etc. in styles.scss

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/product/product.component.scss
> +	.property-table {
Not needed. You deleted property table.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/product/product.component.ts
> +	id: string = '';
Again, no need to use null or empty values.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/quantity-picker/quantity-picker.component.ts
> +	quantity: number = 1;
Quantity should be copied from product

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/components/quantity-picker/quantity-picker.component.ts
> +	incrementQuantity() {
Create a more generic method for incrementing/decrementing quantity.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/enums/icons.enum.ts
> +    minus,
Enums are written with capital letters.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/services/shop.service.ts
> +			.pipe(
If you can't do anything meaningful with an error, don't try to handle it.

2023-08-18 12:04 UTC, JustasVit commented on internship-shop-ui/src/app/services/snack-bar.service.ts
> +			"✅ Order successful",
Create one method for displaying snackbar for success or error. Don't use emoji icons in text.

2023-08-21 06:41 UTC, xonism commented on internship-shop-ui/src/app/components/product-info/product-info.component.html
> +		<span matListItemLine class="list-line">{{product?.description ?? loadingMessage}}</span>
Product description is marked as required in BE so it should always be there

2023-08-21 08:48 UTC, JustasVit commented on internship-shop-ui/src/app/components/quantity-picker/quantity-picker.component.ts
> +	incrementQuantity() {
Maybe it could work like this:

`    if(this.product && this.quantity + value >=1 && this.quantity + value <= this.product.quantity) {
        this.quantity += value;
    }`

2023-08-21 08:50 UTC, JustasVit commented
Looks more or less good for me (read the comment about quantity picker).

2023-08-22 12:24 UTC, ArnasPetraitis approved these changes

2023-08-22 12:24 UTC, merged