#8 | Add product sorting and filtering
xonism/internship-project pull request #22
Opened 2023-08-22 12:46 UTC by xonism

2023-08-22 13:29 UTC, ArnasPetraitis requested changes

2023-08-22 13:29 UTC, ArnasPetraitis commented on internship-shop-ui/.editorconfig
> +indent_size = 3
[unorthodox](https://www.dictionary.com/browse/unorthodox) 😄

2023-08-23 05:40 UTC, JustasVit requested changes
Make sorting or filtering more generic.

2023-08-23 05:40 UTC, JustasVit commented on internship-shop-ui/src/app/app-routing.module.ts
> +	{path: '', redirectTo: '/product-list', pathMatch: 'full'}
use ** wildcard if this is your default page.

2023-08-23 05:40 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-filter/product-filter.component.scss
> +		margin: 1rem 1rem 1rem 0.5rem;
Use short margin version. Better approach would be to move this type of styling to parent tags, buttons etc shouldn't care about margins.

2023-08-23 05:40 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-filter/product-filter.component.ts
> +export class ProductFilterComponent implements OnDestroy {
Better idea would be to have a generic filter component.

2023-08-23 05:40 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-filter/product-filter.component.ts
> +						this.products.filter((product) => product.price >= result[0] && product.price <= result[1]);
Filter option should be generic

2023-08-23 06:19 UTC, xonism commented on internship-shop-ui/.editorconfig
> +indent_size = 3
Disagree - most projects I've seen use this `indent_size` since it seems like the golden middle. 😅
But I'll change it back

2023-08-24 05:39 UTC, JustasVit requested changes
Try to use generics (not mandatory).

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/filter-dialog/filter-dialog.component.html
> +		<button mat-button (click)="onDialogClose()">Cancel</button>
maybe just close()?

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/filter-dialog/filter-dialog.component.ts
> +	constructor(
formatting

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/filter/filter.component.ts
> +	elements!: any[];
If interested, try to do this part with generics.

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/filter/filter.component.ts
> +				const filteredElements: any[] = this.filterService.getFilteredElements(this.elements, filterCriteria);
Move to .emit()

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/product-list/product-list.component.html
> +	<app-sort *ngIf="processedProducts" [selectedSort]="selectedSort" [sortingOptions]="sortingOptions"
After filtering, sorting the product and removing the filter it shouldn't work.

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/product/product.component.html
> +		<app-quantity-picker [product]="product" [quantity]="quantity"
formatting

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/sort/sort.component.ts
> +	emitSelectedSort(sortName: string): void {
formatting

2023-08-24 05:39 UTC, JustasVit commented on internship-shop-ui/src/app/components/sort/sort.component.ts
> +		const sortedElements: undefined | any[] = this.sortService.getSortedElements(this.elements, this.selectedSort);
Make it one-liner.

2023-08-24 06:15 UTC, xonism commented on internship-shop-ui/src/app/components/filter/filter.component.ts
> +	elements!: any[];
Will do it in another PR 😄

2023-08-24 12:04 UTC, JustasVit approved these changes

2023-08-24 12:05 UTC, merged