#8 | Add statistics page
xonism/internship-project pull request #25
Opened 2023-08-25 13:50 UTC by xonism

2023-08-25 14:11 UTC, ArnasPetraitis requested changes

2023-08-25 14:11 UTC, ArnasPetraitis commented on internship-shop-ui/src/app/components/statistics/statistics.component.html
> +		<td mat-footer-cell *matFooterCellDef class="footer">Total</td>
i18n

2023-08-25 14:11 UTC, ArnasPetraitis commented on internship-shop-ui/src/app/components/statistics/statistics.component.ts
> +		return +(order.quantity * order.unitPrice).toFixed(2);
this is not profit 😄  this is total amount sold.  quantity * (priceSold - priceOriginal)

2023-08-25 14:11 UTC, ArnasPetraitis commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/controllers/OrderController.java
> +                : orderService.getAll();
this will kill your system 😄

2023-08-28 05:23 UTC, xonism commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/controllers/OrderController.java
> +                : orderService.getAll();
Realistically, this would be done with pagination 😄

2023-08-28 09:20 UTC, JustasVit requested changes

2023-08-28 09:20 UTC, JustasVit commented on internship-shop-ui/src/app/app-routing.module.ts
> +	{path: 'statistics', component: StatisticsComponent},
product/:id above product

2023-08-28 09:20 UTC, JustasVit commented on internship-shop-ui/src/app/components/statistics/statistics.component.html
> +			'high-profit-row': getOrderProfit(order) >= highProfitThreshold,
ternary op.

2023-08-28 09:20 UTC, JustasVit commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/services/OrderService.java
> +        log.debug("Retrieved orders with startDateTime {} & endDateTime {}:\n{}", startDateTime, endDateTime, orders);
Not necessary.

2023-08-28 09:29 UTC, xonism commented on internship-shop-ui/src/app/components/statistics/statistics.component.html
> +			'high-profit-row': getOrderProfit(order) >= highProfitThreshold,
Values that don't belong to the conditions need to remain without coloring

2023-08-28 09:35 UTC, JustasVit approved these changes

2023-08-28 09:37 UTC, merged