#4 | Add products and users tables
xonism/internship-project pull request #8
Opened 2023-08-07 09:45 UTC by xonism

2023-08-07 13:31 UTC, ArnasPetraitis requested changes

2023-08-07 13:31 UTC, ArnasPetraitis commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/controllers/ProductController.java
> +                products.stream().map(this::convertToDTO).toList(),
streams are more readable when actions are line-breaked.  I would also separated this stream to a variable, e.g. you dont use product list so maping could be done there. e.g.
```
List<ProductDTO> products = productService.getAll()
           .stream()
           .map(this::convertToDTO)
           .toList();
return ResponseEntity.ok().body(products);
```

2023-08-07 13:31 UTC, ArnasPetraitis commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/security/CustomAuthenticationProvider.java
> +public class CustomAuthenticationProvider implements AuthenticationProvider {
This is ok, but is to complicated for current task. Try implement own UserDetailsService and map User to UserDetails there

2023-08-07 13:31 UTC, ArnasPetraitis commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/services/ProductService.java
> +        Product product = productRepository.findById(productSellRequest.id()).orElse(null);
`.orElse(null)` is bad practice. especially when you do  `if (product == null)` on next line. 
```
Product product = productRepository.findById(productSellRequest.id())
     .orElseTrow(()->new ProductNotFoundByIdException(productSellRequest.id());
```

2023-08-09 07:28 UTC, ArnasPetraitis requested changes

2023-08-09 07:28 UTC, ArnasPetraitis commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/services/ProductService.java
>          if (product == null) {
should be removed?

2023-08-09 07:49 UTC, xonism commented on internship-warehouse/src/main/java/com/twoday/internshipwarehouse/services/ProductService.java
>          if (product == null) {
Accidentally didn't commit it 😅 Should be fixed now

2023-08-09 09:34 UTC, ArnasPetraitis approved these changes

2023-08-09 09:36 UTC, merged